// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230427020817_FifthCreate")]
    partial class FifthCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryLkpId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusLkpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("category_lkp_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("status_lkp_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryLkpId");

                    b.HasIndex("StatusLkpId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Domain.CategoryLkp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("category_lkp");
                });

            modelBuilder.Entity("Domain.StatusLkp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("status_lkp");
                });

            modelBuilder.Entity("Domain.SubActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusLkpId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("activity_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("status_lkp_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusLkpId");

                    b.HasIndex("activity_id");

                    b.ToTable("sub_activities");
                });

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.HasOne("Domain.CategoryLkp", "CategoryLkp")
                        .WithMany()
                        .HasForeignKey("CategoryLkpId");

                    b.HasOne("Domain.StatusLkp", "StatusLkp")
                        .WithMany()
                        .HasForeignKey("StatusLkpId");

                    b.Navigation("CategoryLkp");

                    b.Navigation("StatusLkp");
                });

            modelBuilder.Entity("Domain.SubActivity", b =>
                {
                    b.HasOne("Domain.StatusLkp", "StatusLkp")
                        .WithMany()
                        .HasForeignKey("StatusLkpId");

                    b.HasOne("Domain.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("activity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("StatusLkp");
                });
#pragma warning restore 612, 618
        }
    }
}
